### ISSUE TITLE
Gatekeeper keeps Max from starting

### ISSUE THREAD

**Issue by svoop** [sbooth/Max#12]
Sierra has done away with the "download apps from anywhere" option, therefore, Max won't get past the Gatekeeper anymore. (For some odd reason, the exception you can grant by hitting a key after Gatekeeper said "no" does not work for Max.)

As a workaround, it's possible to disable the Gatekeeper very temporarily:
1. `sudo spctl --master-disable`
2. launch Max
3. `sudo spctl --master-enable`

Subsequent launches don't require this workaround anymore.

**Comment by pascalpp** [comment]
FWIW you can right-click on the app and choose Open, and you'll get a slightly different Gatekeeper dialog which allows you to bypass Gatekeeper for Max. You only have to do this once and then you can open the app normally by double-clicking.

**Comment by sbooth** [comment]
All new builds will be signed so this should not be an issue going forward
