### ISSUE TITLE
macOS 10.12.6 breaks Max

### ISSUE THREAD

**Issue by gilgameshskytrooper** [sbooth/Max#15]
I can't get the app open ever since I updated macOS to 10.12.6.

The app shows up as a process, but no GUI components ever show up on the screen.

Thanks

**Comment by kielnino** [comment]
Did you have a CD in your drive? In my case the GUI popped up when I inserted a CD...

**Comment by gilgameshskytrooper** [comment]
I don’t have a cd drive on my computer

**Comment by gilgameshskytrooper** [comment]
Seems that this is now a dead project. Was good while it lasted thanks Max!

Anyways, anyone has the same problem as me after updating OSX, then get XLD. Not as many options as Max, but still does batch conversions without a hitch and is pretty fast.
