### ISSUE TITLE
Provide a 64-bit build

### ISSUE THREAD

**Issue by fortinmike** [sbooth/Max#17]
With the release of macOS 10.13.4, macOS starts warning users about the coming drop of support for running 32-bit apps without compromise: https://support.apple.com/en-ca/HT208436

I just got this warning today with Max (an indispensable tool in my opinion, thanks for making it by the way!). It might be a good idea to update the app to build for 64-bit architectures.

**Comment by ediskrad73** [comment]
Bump. Any chance of this?

**Comment by sbooth** [comment]
Max would benefit greatly from updating to use modern APIs.

**Comment by martinfinke** [comment]
@sbooth I've managed to build a 64-bit version of Max. It's not a 100% automatic process though. My goal was mainly to get a working executable, so I just did some steps by hand, like copying headers into frameworks. But this could be automated as well if someone invests some time. 

If you are interested, I'd be happy to share my changes as a pull request. Most changes are in the AudioFrameworks repository.

**Comment by megadr01d** [comment]
> It's still the best audio converter on macOS by far.

And on Mac OS X ;)

**Comment by sbooth** [comment]
@martinfinke If you are able to submit a PR that would be great!

**Comment by martinfinke** [comment]
Ok! Opened here: #20 and sbooth/AudioFrameworks#11

**Comment by jameslbrown** [comment]
Any updates on a 64-bit version? Really missing Max.

**Comment by sbooth** [comment]
I'm working through updating all of the dependencies. Hopefully I'll have a build to test within a week.

**Comment by sbooth** [comment]
I've posted new frameworks at https://files.sbooth.org/Max-frameworks-20200220.tar.bz2

Using those and current `master` I'm able to build a working, but not thoroughly tested, version of Max that runs on Catalina.

**Comment by sbooth** [comment]
I have posted a new build at https://files.sbooth.org/Max-0.9.2b1.dmg

**Comment by fortinmike** [comment]
@sbooth I tried the app yesterday and it was detected as incompatible by Catalina. I wanted to make sure it was the case by downloading the build again before posting here but the link now leads to a 404.

**Comment by sbooth** [comment]
It should be available again. I was shuffling some stuff on my server.

**Comment by mcandre** [comment]
Letting Homebrew cask devs know about the 64-bit version.

https://github.com/Homebrew/homebrew-cask/issues/79289

**Comment by mcandre** [comment]
Grr, I am also getting 404 for that download link!

**Comment by sbooth** [comment]
ETA for 1.0: unknown

I will host released versions indefinitely but I only leave betas posted if they are current.
