### ISSUE TITLE
macOS Catalina update?

### ISSUE THREAD

**Issue by diogosantos** [sbooth/Max#18]
Hey guys, I just installed Catalina and sadly they don't allow Max to run anymore. How can I survive with the best wav to mp3 converter that exists?

**Comment by HansVanEijsden** [comment]
Ooooh are you serious? Max is one of the most used programs on my Macs. I'm sure I won't upgrade to Catalina if Max won't run.
I've tried to rebuild Max with Xcode from source, but I haven't managed it. I hope to have a solution and/or a successful build for the future. Anyone who can shine a light on this?

**Comment by ediskrad73** [comment]
> Ooooh are you serious? Max is one of the most used programs on my Macs. I'm sure I won't upgrade to Catalina if Max won't run.
> I've tried to rebuild Max with Xcode from source, but I haven't managed it. I hope to have a solution and/or a successful build for the future. Anyone who can shine a light on this?

ive switched to XLD in the meantime

**Comment by aprivette** [comment]
> ive switched to XLD in the meantime

Thank you for this - I guess I'll use XLD as well and hope someone fixes this.

**Comment by federicochiesa** [comment]
I'm not upgrading to Catalina just for this and a few other apps I use... I tried everything to build it from source, I even got it running with dark mode, but as soon as I start a conversion it crashes and I can't fix it.

**Comment by ideoservo** [comment]
I've tried building the sources by myself but having too many issues (unicode problem with Norwegian text files, missing 3rd parties libraries such as Flac, wave pack)...

**Comment by ajmas** [comment]
Also see issue #17 on 64-bit build, since Max is currently limited to 32-bit macOS.

**Comment by sbooth** [comment]
I'm closing this as a duplicate of #17 since the resolution is the same
