### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by ajmas** [sbooth/Max#21]
It would be useful to add a `README.md` to the project. 

I imagine it duplicating some of the information on the main website and then adding more in depth information on building the project.

**Comment by ajmas** [comment]
Trying to build the project myself, from scratch, I am tempted to wan to add some details:

   - Note on code signing and local changes
   - Any dependencies that need to be installed and how to get them

**Comment by sbooth** [comment]
Fixed in b40a84ff953d8511f9207346ffdd6ae9dd8b2e60

**Comment by sbooth** [comment]
The README still needs specifics on building, once I get them hammered out!
