### ISSUE TITLE
Convert Acknowledgments.rtf to markdown

### ISSUE THREAD

**Issue by ajmas** [sbooth/Max#24]
It may be worth converting Acknowledgments.rtf to markdown. The idea being that when viewed in GitHub it would render properly, rather than requiring a download and finding another tool.

**Comment by ajmas** [comment]
Acknowledgments.rtf is used by the app and not just for the source, per krono.

In view of that, I suppose the only way to have it work in both places would be to use a library such as https://github.com/indragiek/CocoaMarkdown

I'll investigate how much work it would be, though at the moment I'll need to wait for the 64-bit work, started by martinfinke, to make some progress.

Could this be of interest?

**Comment by ajmas** [comment]
Not of interest?

**Comment by sbooth** [comment]
I don't think it's worth the effort of integrating a library just to display the acknowledgements.
