### ISSUE TITLE
Sourcing frameworks?

### ISSUE THREAD

**Issue by ajmas** [sbooth/Max#26]
I was looking to see how to bootstrap the projects with the frameworks needed. Is there a process or is it manual. If the latter, would you be interested in using something like CocoaPods?

**Comment by ajmas** [comment]
I did look at CocoaPods, but it does not seem to provide all the necessary frameworks needed by the project.

**Comment by sbooth** [comment]
I have posted new frameworks at https://files.sbooth.org/Max-frameworks-20200220.tar.bz2

It is currently a painful manual process.

**Comment by ajmas** [comment]
Get a 404 for: https://files.sbooth.org/Max-frameworks-20200220.tar.bz2
