### ISSUE TITLE
Crashes whenever it uses internet (0.9.2b2)

### ISSUE THREAD

**Issue by ctsde-markus** [sbooth/Max#34]
Hi!

I'm on macOS 10.14.6 Mojave and Max 0.9.2b2 always crashes whenever it uses internet. Wheter it's MusicBrainz or trying to fetch a cover. Checking for a new version works as expected though.

Anything i can do to help track this down?

I am in a WiFi network using a proxy (via auto discovery), but even if i completely deactivate the proxy Max crashes.

And of course, when i try to reproduce it, it doesn't crash (it crashed EVERY DAMN TIME I TRIED IT BEFORE!). As if it knew that i'll going to report that.

Anyone else experienced such a crash?

**Comment by ctsde-markus** [comment]
Ah! Now it crashed again. I saved the crash report, but i'd rather not publish it here world-readable. Please ask when you need it.

**Comment by sbooth** [comment]
@ctsde-markus Please send the crash report to me@sbooth.org

**Comment by sbooth** [comment]
This seems to only be a problem with the German localization.
