### ISSUE TITLE
can't encode mp3s from 24 bit

### ISSUE THREAD

**Issue by custerflux** [sbooth/Max#36]
Max version 0.9.2b2 doesn't seem to be able to process 24-bit audio into MP3 correctly.  Whatever the samplerate, 24-bit audio gets encoded into total silence.  It will encode properly to other formats besides MP3, and 16-bit audio seems to pass through everything just fine.

**Comment by timnyss** [comment]
Same issue. This only happened since I updated to Catalina a few weeks ago.

**Comment by sbooth** [comment]
This was an interesting bug that also affected to 32-bit source data. `lame_encode_buffer_long2()` expects the values to be scaled to fit the size of `long`, not a particular bit width. Max was assuming 32-bit scaling.

**Comment by sbooth** [comment]
Max-0.9.2b3 is now available and contains the fix.

**Comment by timnyss** [comment]
Many thanks!!!!!

**Comment by custerflux** [comment]
Works great!  Thank you.

**Comment by sbooth** [comment]
In hindsight it would be easier to use `lame_encode_buffer_ieee_float()` for all bit depths but I don't think that API existed in LAME 3.95 when this code was originally written.
