### ISSUE TITLE
AudioMetadata.mm fails to build from source in xcode 6.2 under MacOS 10.9

### ISSUE THREAD

**Issue by poetnerd** [sbooth/Max#4]
I get the error: Cannot initialize return object of type 'NSString *' with an rvalue of type 'NSNumber *'
on lines 333, 340, 370,377:

333: (NSString *)	trackDate					{ return [[_trackDate retain] autorelease]; }
340: (NSString *)	albumDate					{ return [[_albumDate retain] autorelease]; }
370: (void)		setTrackDate:(NSString*)trackDate				{ [_trackDate release]; _trackDate = [trackDate retain]; }
377: (void)		setAlbumDate:(NSString *)albumDate				{ [_albumDate release]; _albumDate = [albumDate retain]; }

I see that album and track "Year" are used elsewhere.  Is this a conversion between "Year" and "Date" that didn't get consistently applied when the repository was recovered.

I'd very much like to communicate with others who are building Max from source.

**Comment by poetnerd** [comment]
I think I may have a solution.

Theory: the code snapshot was indeed across a change from "the year integer" to "the date string".
Changing lines 30 and 37 to change trackDate and albumDate from NSNumber to NSString silenced the error.

**Comment by sbooth** [comment]
This was a bug.  I just pushed a bunch of changes and this fix was included.
