### ISSUE TITLE
Can't build on Xcode 12.4

### ISSUE THREAD

**Issue by davecarlson** [sbooth/Max#40]
Getting the following error: 
```
[NSDecimalNumber Length]:unrecognized selector sent to instance
```
It seems it's the number formatter for the progreess field, but can't seem to fix it my end.

Happens in encoder.xib and ripper.xib

**Comment by sbooth** [comment]
The current `master` branch (cbb668e3e04644a7d5b0cc20b95ea86257442d2f) builds using Xcode 14.2.
