### ISSUE TITLE
Website/download links down?

### ISSUE THREAD

**Issue by woj-tek** [sbooth/Max#47]
When trying to open the page https://sbooth.org/Max/ I get "403 Forbidden".

File download from https://files.sbooth.org/ fails completely with "server not found"

**Comment by sbooth** [comment]
I recently switched hosting providers and haven't quite finished the move. I will set up the files subdomain soon.

**Comment by woj-tek** [comment]
Any chance of hosting releases on github? :-)

**Comment by sbooth** [comment]
In the future that is definitely a possibility. But for now https://files.sbooth.org is live again so hopefully downloads are working.

**Comment by woj-tek** [comment]
Awesome, it's working again, thank you! :-)
