### ISSUE TITLE
Cannot select quality of Core Audio encoding, defaults to Minimum

### ISSUE THREAD

**Issue by akemn** [sbooth/Max#6]
As of 10.11 (El Capitan), the quality selection for Core Audio encodings is nonfunctional. "Minimum" quality appears selected by default and is unchangeable.

See here for the same report by another user: http://forums.sbooth.org/viewtopic.php?f=4&t=98737

**Comment by sbooth** [comment]
I can confirm this is a problem but I'm not sure what changed in Core Audio to cause it.
