### ISSUE TITLE
When it actually works

### ISSUE THREAD

**Issue by kambysese** [sbooth/Max#7]
Column identifiers used with NSTableView autosave feature must conform to NSCoding protocol: (null)

**Comment by sbooth** [comment]
I believe this has been fixed in the latest git commit

**Comment by kambysese** [comment]
@sbooth It doesn't look like the commit has been added to the [0.9.1 binary](http://sbooth.org/Max/#download) I downloaded yesterday. Ended up going with XLD, feel free to close.
