### ISSUE TITLE
Problem using MusicBrainz data for 2 cd release

### ISSUE THREAD

**Issue by hartzell** [sbooth/Max#8]
I'm new to Max.  I'm trying to rip [Performing This Week… Live at Ronnie Scott’s (Deluxe Edition)](https://musicbrainz.org/release/7a61e901-4d2f-4b9d-9cee-f27e8ecbf1b6).

It's a two disk release.  The first disk went perfectly; I was offered several matches from MusicBrainz, chose the Deluxe set, and away I went.

I'm having trouble with the second disk.  Max finds the correct release, but doesn't seem to understand that it's the second disk of the set instead uses the title info for the first 12 of 16 tracks from the first disk.

Is there a way that I can get to Do The Right Thing?

**Comment by CatQuest** [comment]
I also have this issue
note, that Musicbrainz has changed the way it handled multi-disc releases since the Last stable release of Max.
also it seems Max is not being actively developed any longer, which is a shame, as it's a great tool.

**Comment by reosarevok** [comment]
For what it's worth: the solution for this is moving away from the deprecated version 1 of the web service and to version 2.

**Comment by megadr01d** [comment]
Or [version 3](https://github.com/doshidak/Max/commit/97023547ed0e43cd2d9ec3a49ec5ca322e5be209).

**Comment by sbooth** [comment]
I've updated to libmusicbrainz5 and the newer v2 web service. I haven't had a chance to extensively test it.

**Comment by sbooth** [comment]
Tangentially related to #37

**Comment by sbooth** [comment]
Max 0.9.2b4 is available and contains this fix
